### ISSUE TITLE
[request] Batch encoding of images one at a time

### ISSUE THREAD

**Issue by schoolruler** [kornelski/cavif-rs#14]
I'm trying to encode many avif images at the same time. Even though cavif supports doing them at the same time the total ram required builds up. Would it be possible to add an argument that allows for batch encoding one image at a time for the sake of using less ram at a given time?

**Comment by kornelski** [comment]
Try setting `RAYON_NUM_THREADS` env var.

```rust
export RAYON_NUM_THREADS=1
```

for single-threaded encoding (or adjust 1 to whatever number you find acceptable).
