### ISSUE TITLE
thread count

### ISSUE THREAD

**Issue by dbquarrel** [kornelski/cavif-rs#16]
cavif takes a number of threads equal to available cores on the host... it would be nice to have a parameter to limit or control the number of threads being launched for fine tuning / resource management on large amounts of bulk processing.

**Comment by kornelski** [comment]
Makes sense. 

Can you give it a try and make a PR that adds --threads arg?

**Comment by dbquarrel** [comment]
I don't know rust but I'll give it a shot.

**Comment by dbquarrel** [comment]
Done.
