### ISSUE TITLE
speed = 0

### ISSUE THREAD

**Issue by dbquarrel** [kornelski/cavif-rs#17]
Documentation says that the lowest accepted parameter for speed is 1 and this is best quality. Passing in a value of zero works, produces a smaller image file but the processing time is about 10x slower than speed 1.

So, two parts:

1. docs should reflect that speed = 0 can be passed in
2. it would be nice if there was a finer level of granularity than an order of magnitude (doubling makes sense), not sure if this is inside the encoder though rather than at the application level so might be out of scope

**Comment by kornelski** [comment]
Yeah, the speed is passed straight through to rav1e. Given how unbalanced speed 0 is, maybe it's best to leave it as an easter egg ;)
