### ISSUE TITLE
Add a homebrew tap for osx?

### ISSUE THREAD

**Issue by kljensen** [kornelski/cavif-rs#19]
You can see an [example here](https://github.com/kljensen/homebrew-misctap/blob/main/Formula/cavif-rs.rb) that shows how to compile cavif-rs from source on osx using homebrew.

(Thanks for this wonderful tool.)

**Comment by kornelski** [comment]
If you'd like to submit it to Homebrew, then go ahead.

**Comment by kljensen** [comment]
Thanks @kornelski. I don't want to. I raised it merely in case you wished to. I'll close the issue.
