### ISSUE TITLE
Saving AVIFs with different names to different directories

### ISSUE THREAD

**Issue by kgollert** [kornelski/cavif-rs#22]
Sadly the following is not working, as `-o` creates a directory and the hashed original filename is taken:

`cavif -q 60 -s 6 /app/storage/runtime/imager/temp/2857c3cd15a554c56dda07e564382c37.png -o /app/web/imager/root/3284/person-home_7fdd2710.avif`

Is there a way to `cavif foo/foo.jpg -o foobar/bar.avif`?

**Comment by kornelski** [comment]
`-q` means quiet operation, not quality. This makes `60` interpreted as a file, so `-o` is interpreted as a directory, because you can't write two files to one filename.
