### ISSUE TITLE
add arm binary versions

### ISSUE THREAD

**Issue by superbonaci** [kornelski/cavif-rs#23]
Could be possible to add arm binaries, at least for Windows and Linux?

**Comment by kornelski** [comment]
The project is compatible with ARM, so if you have an ARM machine, you should be able to compile it there. https://github.com/kornelski/cavif-rs#building

I might be able to cross-build for Linux, but I don't have that set up yet. 

I have no idea how to cross-build for Windows+ARM.

**Comment by superbonaci** [comment]
Maybe you don't need to cross compile, I think it's possible to setup arm guests with QEMU inside x86_64 hosts.

**Comment by kornelski** [comment]
I've used quemu for a while, but it's been slow and unstable. It doesn't support new syscalls, so requires appropriately old versions of the OS under emulation.

Rust cross-compilation for ARM Linux works pretty well, and I use in production at work, but for my home projects I haven't got time to set up appropriate build environment. System administration isn't something I do for leisure :)

So for now if you have ARM machines, I recommend that you build there, or set up a cross-build or emulation for your needs.

**Comment by superbonaci** [comment]
No problem, I'll try when needed.
