### ISSUE TITLE
Lossless support?

### ISSUE THREAD

**Issue by adworacz** [kornelski/cavif-rs#24]
Forgive my ignorance wrt AVIF, but I believe that AVIF supports a "lossless" mode.

Looking at the README for `cavif` there doesn't appear to be any mention of a lossless mode. Is `--quality 100` lossless, or is proper lossless support not implemented at this time?

**Comment by kornelski** [comment]
There's no lossless support, because rav1e doesn't support it. Besides, truly lossless mode in AVIF is not competitive. It only does a pretty good job as visually-lossless.

**Comment by adworacz** [comment]
Got it.

Since I'm sure I'm not the only one who'll have this question, mind if I put a PR together that adds a FAQ section to the README with this answer?

**Comment by kornelski** [comment]
Done
