### ISSUE TITLE
Cannot install `cavif 1.0.0` on Windows 10

### ISSUE THREAD

**Issue by nikonthethird** [kornelski/cavif-rs#26]
Note at the beginning: I have no issues installing `cavif 0.6.6`.

I cannot upgrade from `cavif 0.6.6` to `cavif 1.0.0` on Windows 10. NASM is in the path with the most recent version:

```text
PS C:\Users\Nikon the Third> nasm --version
NASM version 2.15.05 compiled on Aug 28 2020

PS C:\Users\Nikon the Third> rustc --version
rustc 1.51.0 (2fd73fabe 2021-03-23)
```

But when I run `cargo install cavif`, I get these errors, and the build fails:

```text
...
  C:\Users\Nikon the Third\.cargo\registry\src\github.com-1ecc6299db9ec823\rav1e-0.5.0-alpha\src/x86/sse.asm:472: warning: trailing garbage after macro name ignored [-w+other]
  C:\Users\Nikon the Third\.cargo\registry\src\github.com-1ecc6299db9ec823\rav1e-0.5.0-alpha\src/x86/sse.asm:442: ... from macro `WEIGHTED_SSE' defined here
  thread 'main' panicked at 'NASM build failed. Make sure you have nasm installed. https://nasm.us: "failed to spawn process: The system cannot find the file specified. (os error 2)"', C:\Users\Nikon the Third\.cargo\registry\src\github.com-1ecc6299db9ec823\rav1e-0.5.0-alpha\build.rs:120:6
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I opened one of these `.asm` files and they look fine. Installing cavif 0.6.6 works fine on the other hand:

```text
PS C:\Users\Nikon the Third> cavif --version
cavif-rs 0.6.6
```

I installed an Ubuntu VM on the same machine, there cavif could be installed no problems. Any suggestions?

**Comment by kornelski** [comment]
It looks like incompatibility between rav1e and nasm. I've reported it upstream.

**Comment by kornelski** [comment]
It'll be fixed in the next release. In the meantime, you could ensure `ar` is in your `PATH`.
