### ISSUE TITLE
Is it possible to compile `ravif` to WebAssembly?

### ISSUE THREAD

**Issue by nikonthethird** [kornelski/cavif-rs#30]
This is just a question, really, I have not tried anything yet.
Is it possible to compile `ravif` to a `.wasm` file for use in a browser?

Are there any feature flags I have to be aware of (like the `wasm` feature for `rav1e`)?

**Comment by kornelski** [comment]
Sure, it already works.

**Comment by nikonthethird** [comment]
Thank you!
