### ISSUE TITLE
debug assertion triggers (Segmentation Fault in --release)

### ISSUE THREAD

**Issue by AxelMontini** [kornelski/cavif-rs#31]
I'm using the `ravif` to encode a sequence of bytes inside a tokio blocking task.
Calling the encode function triggers a debug assertion, which turns into a segfault in release.
The code is the following:
```rust
let resized_img = img_full.resize(w, h, image::imageops::FilterType::Lanczos3);
let bytes = resized_img.to_rgba8();
let encoded = ravif::encode_rgba(ravif::Img::new(bytes.as_rgba(), w as _, h as _), &config);
```

The error I get in debug mode is the following:

```
thread 'tokio-runtime-worker' panicked at 'assertion failed: img.buf().len() + stride >= stride * img.height() + width.get()', /home/axel/.cargo/registry/src/github.com-1ecc6299db9ec823/imgref-1.9.0/src/iter.rs:185:9
```

**Comment by kornelski** [comment]
What's the size of the input image? Can you share the image?

**Comment by AxelMontini** [comment]
Sorry it it took long to reply.
I've narrowed down the cause of the issue to transparency.

I tried many images without the alpha channel, both bigger and smaller than `w` and `h`. No error was produced and the image was encoded correctly.

Transparent images, on the other hand, cause a Segmentation Fault when encoded.

Here's a longer and more complete piece of code that is causing the issue:
```rust
/// Reads the avatar by guessing the format and returns the dynamic image
async fn read_avatar(p: PathBuf) -> image::DynamicImage {
    let img_bytes = tokio::fs::read(p).await.expect("reading avatar");
    let img_full = image::io::Reader::new(Cursor::new(img_bytes))
        .with_guessed_format()
        .expect("determine image format")
        .decode()
        .expect("decoding image");

    img_full
}

async fn encode_avatar(
    img_full: image::DynamicImage,
    w: u32,
    h: u32,
) -> Result<Vec<u8>, Box<dyn std::error::Error + Send + Sync>> {
    let config = ravif::Config {
        quality: 80.0,
        alpha_quality: 60.0,
        speed: 3,
        premultiplied_alpha: false,
        color_space: ravif::ColorSpace::YCbCr,
        threads: 1,
    };

    let img = img_full.resize(w, h, image::imageops::FilterType::Lanczos3);
    let img = img.to_rgba8();

    tokio::task::spawn_blocking(move || {
        info!(w, h, "Encoding avatar");
        ravif::encode_rgba(ravif::Img::new(img.as_rgba(), w as _, h as _), &config)
            .map(|(i, _, _)| i)
    })
    .await
    .expect("spawning encoding task")
}
```

The worrying part is that a Segfault is produced in safe code. I propose that the function should either panic or return an error when the size of the buffer doesn't match `w` and `h`.

The two transparent images I've tested are [The GitHub logo](https://assets.stickpng.com/images/5847f98fcef1014c0b5e48c0.png) and [this](https://liquipedia.net/commons/images/c/ce/Bandit_R6S.png)

**Comment by kornelski** [comment]
You are most likely passing RGB pixels to a function that expects RGBA. The `to_rgba8`/`as_rgba` functions probably don't check if the conversion is valid, and reinterpret A pixels as one of the RGB channels.

Before `encode_rgba` put:

```rust
assert!(img.as_rgba().len() >= w * h);
```

I'm betting this is the problem.

**Comment by AxelMontini** [comment]
I understand that one should assert before passing an image, but the issue is that the error is a segmentation fault in release, a thing that rust should prevent. This means that somewhere `unsafe` is being used incorrectly.

The debug assertion in imgref should ideally be turned into a normal assertion that prevents memory unsafety in release too.

**Comment by kornelski** [comment]
I've updated assertion there. Run `cargo update`
