### ISSUE TITLE
CAvif 1.3.0 creates invalid Avif files for Chrome

### ISSUE THREAD

**Issue by mongeron** [kornelski/cavif-rs#34]
After Chrome 92 arrived, many of the AVIF images on my websites started showing corrupt image icon in Chrome 92. Images were created with CAvif 0.6.0.

I updated CAvif to 1.3.0 and re-encoded all images. However, some of the AVIF images are still broken in Chrome 92.

I can provide sample images of original JPEG files and broken AVIF files if needed.

**Comment by kornelski** [comment]
Can you share an example image and exact Chrome version?

**Comment by mongeron** [comment]
https://www.bonusfinder.com/images/rsz_caesars07262021-800x331.jpg.avif contains the broken encoded image, https://www.bonusfinder.com/images/rsz_caesars07262021-800x331.jpg contains the original source image.

Command line used for conversion:

`cavif -f -s 1 -Q 55 rsz_caesars07262021-800x331.jpg -o rsz_caesars07262021-800x331.jpg.avif`

Chrome:

Google Chrome is up to date
Version 92.0.4515.107 (Official Build) (x86_64)

Operating system is MacOS.

**Comment by kornelski** [comment]
I can't reproduce it. The AVIF file looks like from an older version.

**Comment by kukulich** [comment]
Btw we had also problems with Chrome 92 but upgrade to 1.3.0 fixed it for us.

**Comment by mongeron** [comment]
I am pretty sure it was generated using the newer version, but I will double-check.

**Comment by mongeron** [comment]
It was indeed encoded by the old version, sorry for the false alarm.

**Comment by kornelski** [comment]
Phew
