### ISSUE TITLE
Binrary releases 1.3.0 and 1.3.1 contain version 1.2.0 for windows

### ISSUE THREAD

**Issue by nocduro** [kornelski/cavif-rs#36]
I'm having trouble getting firefox to load images from cavif and found issue #33
Thought I'd try the latest released version to see if that helped, but turns out there is an older windows version in the releases .zip file. Both the 1.3.0 and 1.3.1 [releases](https://github.com/kornelski/cavif-rs/releases) contain version 1.2.0 for windows.

Building with `cargo install cavif` gives 1.3.0 on windows, and building from source in git gives 1.3.1

**Comment by kornelski** [comment]
Thanks. Fixed.
