### ISSUE TITLE
Chrome 93.0.4577.63 doesn't seem to like 1.3.0 

### ISSUE THREAD

**Issue by BrianLeishman** [kornelski/cavif-rs#38]
Seems to work great in 92.0.4515.131. I had images that suddenly stopped working in Chrome maybe a month or two ago, and rebuilding them all with 1.3.0 seemed to fix them, but now with this Chrome update *some* of my images are not loading anymore. I've attached an example one, confirmed it's definitely being converted with 1.3.0. 

Same exact behavior with the previous Chrome breaking things where Chrome gives no errors, just decides not to show anything.

Going to test with 1.3.1 but it doesn't look like that version fixed compatibility issues so I don't think that'll be the fix, maybe the same issue as the latest Firefox version?

[converter.zip](https://github.com/kornelski/cavif-rs/files/7122022/converter.zip)

**Comment by kornelski** [comment]
That should be fixed by:

https://github.com/AOMediaCodec/libavif/pull/745

I was told it would make into Chrome 93, but apparently it didn't.
