### ISSUE TITLE
Support APNG?

### ISSUE THREAD

**Issue by yisibl** [kornelski/cavif-rs#44]
Are there any plans to support APNG?

**Comment by kornelski** [comment]
No. I have no plans to ever support "animation". I find this concept absurd. It's especially ridiculous in the case of MP4+AV1 "animation" vs MP4+AV1 "video" which is the exact same thing, just with different metadata attached.

I think the myth of "animaion" existing as a concept is only kept alive by technical debt in the Blink engine (in Chrome). They would rather maintain two codecs with two decoders for the same thing, than to sort it out to allow sound-less video files in `<img>`, like Safari does.
