### ISSUE TITLE
build error: failed to select a version for the requirement `ravif = "^0.8.6"`

### ISSUE THREAD

**Issue by baumanj** [kornelski/cavif-rs#46]
```
$ cargo update
error: failed to select a version for the requirement `ravif = "^0.8.6"`
candidate versions found which didn't match: 0.8.5
location searched: /Users/jbauman/src/cavif-rs/ravif
required by package `cavif v1.3.2 (/Users/jbauman/src/cavif-rs)`
```

Should the `ravif` crate version have been increased to 0.8.6 in https://github.com/kornelski/cavif-rs/commit/8085008cd1cb6d825c4cb7ff3bb10f86b2d11997 ?

**Comment by kornelski** [comment]
That's odd. 0.8.6 has been published in August.

https://lib.rs/crates/ravif/versions

**Comment by kornelski** [comment]
I've bumped minor ver and published again.
