### ISSUE TITLE
Premultiplied alpha support is broken since v0.6.4

### ISSUE THREAD

**Issue by baumanj** [kornelski/cavif-rs#48]
It looks like the flag was left out of the transition to the new args parser in a95b3c285db85696999bf7f7eefd051680491d30. The following addition is sufficient to get the code running again:
```diff
diff --git a/src/main.rs b/src/main.rs
index fd93c31..6199377 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -75,6 +75,9 @@ fn run() -> Result<(), BoxError> {
         .arg(Arg::with_name("dirty-alpha")
             .long("dirty-alpha")
             .help("Keep RGB data of fully-transparent pixels (makes larger, lower quality files)"))
+        .arg(Arg::with_name("premultiplied-alpha")
+            .long("premultiplied-alpha")
+            .help("Alternative compression mode that lowers quality of semi-transparent colors. Warning: at low qualities it may create black artifacts in transparent areas."))
         .arg(Arg::with_name("color")
             .long("color")
             .default_value("ycbcr")
```
However, the output it generates is invalid per ISOBMFF (ISO 14496-12:2020) § 8.11.12.1 since it requires "Zero or one" `iref` boxes and [the output generated](https://github.com/kornelski/cavif-rs/files/7228085/partially-transparent-green.cavif-aa19c15-prem.avif.zip) has 2.

**Comment by kornelski** [comment]
The [dirty-alpha workaround](https://github.com/kornelski/cavif-rs/blob/main/ravif/src/dirtyalpha.rs#L50) I've developed turned out to work much better than I expected, so I've decided to drop support for premultiplied alpha.
