### ISSUE TITLE
Chrome 96 issue

### ISSUE THREAD

**Issue by vladbondarenko** [kornelski/cavif-rs#50]
Hello, images from 1.3.1 worked fine untill Chrome 96, 95 was ok but 96 not. Can this be fixed on your side or it was broken on google side?

**Comment by baumanj** [comment]
See https://bugs.chromium.org/p/chromium/issues/detail?id=1198455#c53

The short version is that cavif-rs previously wasn't associating the required `ispe` (read: image dimensions) property with the alpha planes for transparent images. That led to Chrome temporarily making an exception for that issue, but now that they've added the check back, images generated with the old version of cavif-rs are breaking again.

I don't think there's anything to do on the cavif-rs side for this.

**Comment by vladbondarenko** [comment]
i see that there is cavif 1.3.3 on crates.io (compiled binary), @kornelski is it possible to build the 1.3.3 release here?

**Comment by kornelski** [comment]
1.3.3 is released.
