### ISSUE TITLE
Install NASM per build script

### ISSUE THREAD

**Issue by johannesvollmer** [kornelski/cavif-rs#52]
Hi!

Performance is great, but manually installing the NASM dependency is a hassle. To increase the usability of this crate, it would be nice if a build script handled the installation, and maybe if it fails, deactivate the feature as a fallback. Is such a [build script](https://doc.rust-lang.org/cargo/reference/build-scripts.html) possible with NASM?

**Comment by kornelski** [comment]
No, Cargo build scripts are not allowed to change the operating system. They could download a private copy of nasm, but that's a weird hack.

Use pre-built binaries if you don't want to install dev dependencies.

**Comment by johannesvollmer** [comment]
What about building a local nasm from a copy of local nasm source code in the build script? Isn't this possible with nasm?

**Comment by kornelski** [comment]
It is possible, but I don't think that's a sensible path to pursue. To build nasm I'd need in addition to a C compiler toolchain, autotools and Perl, which not every platform has, so this moves the problem by one step: should I build autotools and Perl too? And their dependencies?

Nasm has packages for every Linux distro, Mac Homebrew, and an installer for Windows, so it's not that difficult to get. 

I'm providing pre-build binaries for cavif, so *users* don't need to install nasm. It's only required for building from source, and I think it's reasonable to ask developers to install a common developer tool.
