### ISSUE TITLE
'error: too many pixels, not supported' on large files

### ISSUE THREAD

**Issue by Shnatsel** [kornelski/cavif-rs#54]
Trying to convert a 14k by 20k image to AVIF with `cavif` fails with the following error: `too many pixels, not supported`

The error [comes from lodepng](https://github.com/kornelski/lodepng-rust/blob/72ec082d26c9c5ede84c521f1df571823e944f88/src/error.rs#L197).

**Comment by Shnatsel** [comment]
Perhaps consider using the `png` crate which supports large images? I've checked the exact image I'm trying to convert, and it does decode correctly with the `png` crate.

**Comment by kornelski** [comment]
Yeah, maximum size lodepng allows is 268435455 pixels. This is inherited from the C implementation, which probably had to be more cautious about integer overflows. I've allowed bigger images on 64-bit machines.

**Comment by Shnatsel** [comment]
Has the fix been released to crates.io? I'm still getting the same error with cavif v1.3.4 and lodepng v3.6.1, which are the latest versions as of this writing. I also cannot see any relevant changes in git master in either cavif or lodepng repositories.

**Comment by kornelski** [comment]
Sorry, I forgot to push it. It's v3.6.2
