### ISSUE TITLE
can we convert PNG with specified sampling format？

### ISSUE THREAD

**Issue by woshilaiba** [kornelski/cavif-rs#58]
First，thank you for this very helpful tool ！
In my case， convert the png file to avif ，I found that it will generate a pink stripe at the right edge of the png file.
It is the same situation in AOMediaCodec/libavif  when encoding with the " -y 444" option, but not with "-y 420" or "-y 422"
So, i guess it (Chroma Subsampling) is the cause of this little problem.

CLI:  cavif -Q 50 test.png
the original image for test:
![Tray](https://user-images.githubusercontent.com/20653360/180120452-7729a1b9-a31d-4259-b4e8-ad7a6ded23ad.png)

after convert like this( a jpeg for just show what it looks like):
![image](https://user-images.githubusercontent.com/20653360/180120800-387eb8d4-48b0-4542-a792-ffcaf0aab359.png)

Thank U!

**Comment by kornelski** [comment]
This crate always uses 444 (highest resolution) color sampling, so it isn't supposed to cause any distortions like this. 

Do I understand correctly that you've encoded this image using different tool and still saw the incorrect line? In such case it's a bug in the decoder, not the encoder. 

I would prefer to kill chroma subsampling for good. AV1 handles color well and doesn't need to continue the tradition of using a mathematically-incorrect ugly hack for an analog TV signal from more than half century ago.

**Comment by woshilaiba** [comment]
> This crate always uses 444 (highest resolution) color sampling, so it isn't supposed to cause any distortions like this.
> 
> Do I understand correctly that you've encoded this image using a different tool and still saw the incorrect line? That would suggest it's a bug in the decoder, not the encoder.

I've encoded this image using "avifenc"， the cli is "**avifenc  -y 444 tray.png tray_avifenc.avif**", and using "cavif" with "**cavif -Q 50 tray.png**" .
**They both get the incorrect line** at the right edge, but **It is correct when I encode it with "avifenc  -y 422 xxxx.png xxx.avif"**.
I'm not familiar with "Chroma Subsampling", just a guess!


operating system: Windows 10 subsystem for linux

**Comment by eugenesvk** [comment]
I've read in [this blog](https://nuvs.tech/en/10911/) that the vertical bar is an issue with Microsoft Photos, so might indeed be a decoder issue
> Additionally, for avif images created by libavif, Microsoft Photos will have a strange vertical color bar on the right side of the images when the format is set to YUV444

**Comment by kornelski** [comment]
Yup, I think it's a decoder issue.
