### ISSUE TITLE
[FR] Output to a specific filename+path

### ISSUE THREAD

**Issue by aelvan** [kornelski/cavif-rs#6]
It would be nice if there was a way to specify the _filename_ (with path) that a converted file is saved to. I initially thought that that's what `-o` is for, but that's only the path, there doesn't seem to be a way to save to another file format? 

For context, I'm trying to use cavif as an encoder together with my [Imager X plugin for Craft CMS](https://imager-x.spacecat.ninja/usage/avif.html#configuring-avif-support-in-imager-x), and I need to be able to create a single cli command that encodes a temporary source image file to a target avif file. With avifenc I'm able to do it with a template that's `--min {minQ} --max {maxQ} --speed {speed} {src} {dest}`, for instance. 

Would be cool if something like that could be done with cavif in the future.

**Comment by kornelski** [comment]
I don't understand. `caviv -o file.avif file.jpg` works.

**Comment by aelvan** [comment]
You're absolutely right! I had the options wrong, I was using `-q 80 -s 3` instead of `--quality=80 --speed=3`, and for some reason, that makes cavif put the files in a folder. Probably because it thinks it's more than one image? Anyways, my fault, sorry! :)

**Comment by kornelski** [comment]
Indeed, it looks like unknown args fail like that. Thanks for pointing that out. I'll switch to a smarter arg parsing library.
