### ISSUE TITLE
Converted images sometimes get orange/magenta overlays on the right edge

### ISSUE THREAD

**Issue by JSorngard** [kornelski/cavif-rs#60]
It is clearest in this screenshot:
![bunny_artifact](https://user-images.githubusercontent.com/44257381/201489017-6764f53d-f41e-4394-91b1-336229543fe0.png)

I have been unable to determine exactly what causes this, because some images convert just fine (this one was first converted to png with windows paint and then to avif with cavif):

![eso_fine](https://user-images.githubusercontent.com/44257381/201489067-541fefd9-99c6-4cdf-9f1d-d336611e0fe8.png)

The affected edge seems to be of constant size in pixels, because larger images have a smaller edge:

![large_affected](https://user-images.githubusercontent.com/44257381/201489203-6bef7968-6776-47ac-b34e-9fd5499debe9.png)

This is on windows with the latest version.

These are the affected images for debugging:
[BUNNY!](https://user-images.githubusercontent.com/44257381/201489302-7e2644c5-81a1-48de-965a-762a7c103065.PNG)
[2K3vqjE](https://user-images.githubusercontent.com/44257381/201489305-347b87bc-c39c-4b21-9838-65ce26a393d8.jpg)

This is an unaffected image:
[BcFu4F9](https://user-images.githubusercontent.com/44257381/201489391-7d7c47bb-de15-45d9-808f-96849d639669.jpg)

**Comment by JSorngard** [comment]
This is on windows

**Comment by kornelski** [comment]
I believe that the files are correct, and this is a bug in Windows' AVIF preview. 

There is workaround for Windows, but it requires halving resolution of color channels. I'd rather not do this, because it degrades color quality for everyone.

**Comment by JSorngard** [comment]
I see. The colored band is there when opened in Windows photo viewer and
paint, but not when I open it in Firefox, so it seems its on Microsoft's
end. Thank you for the fast answer!

Den lör 12 nov. 2022 20:54Kornel ***@***.***> skrev:
