### ISSUE TITLE
Add a flag to save the original creation date of the image

### ISSUE THREAD

**Issue by valsaven** [kornelski/cavif-rs#63]
Greetings, thank you for the awesome library!
Is it possible to add a flag to save the original creation date of the image? This can be useful for converting various photo collections.

**Comment by kornelski** [comment]
I'm not planning to preserve EXIF data, which is usually the authoritative source for date a photo was taken in photo collections. It's not a good idea to use this tool for photo collections.

If your photos are in JPEG, try using JPEG repacker feature of JPEG XL.
