### ISSUE TITLE
Update help message re. quality

### ISSUE THREAD

**Issue by eugenesvk** [kornelski/cavif-rs#64]
The help message re. quality is "Quality from 1 (worst) to 100 (best). NB! Not the same scale as JPEG quality"
However, the new release mentions that "The --quality setting has changed to match behavior of quality settings in JPEG and WebP encoders. Most reasonable values are now between 70-80"
So should the help message be updated or is there still something more complicated re the scale difference?

**Comment by kornelski** [comment]
Well, it's not wildly different as before, but still "it's complicated", and results vary depending on image content.

**Comment by kornelski** [comment]
5c931cbe09a2f3d3834409c82fb049d6be948af3
