### ISSUE TITLE
10-bit encoding is not available

### ISSUE THREAD

**Issue by MeiLaii** [kornelski/cavif-rs#65]
I am using cavif.exe from release v1.5.0.
 When converting RGB24 png images, I get 8-bit depth avif instead of 10-bit depth avif. 
Is this a bug or is this expected behavior?

**Comment by kornelski** [comment]
Opaque RGB encoding should use 10-bit depth. Encoding of RGBA images will still use 8-bit depth, because I was unable to get 10-bit RGBA working in Safari (10-bit files with alpha that display fine in Firefox and Chrome show garbage in Safari and iOS/macOS Ventura).

**Comment by MeiLaii** [comment]
I upgraded to v1.5.1 and everything is working as expected. Thanks!
