### ISSUE TITLE
No way to do 8 bit encoding any more ?

### ISSUE THREAD

**Issue by femski** [kornelski/cavif-rs#69]
There is no option for 8 bit encoding anymore. My decoder crashes on 10 bit.

**Comment by kornelski** [comment]
For now if the image contains an alpha channel, it will still use 8 bit.

Which decoder do you use?

**Comment by femski** [comment]
Never mind. I figured how to get 10 bit decoder to work

I am using libavif/dav1d in web assembly and having a difficult time getting decoding to work in WASM (crashes on all images produced by avifenc and imagmagick - both based on libavif I believe)). In fact cavif/rav1e now is the only encoder that produces something reasonably good quality that works for me. New version 1.5.0 seems very fast (AVX improvement?). Thank you!

**Comment by baumanj** [comment]
> avifenc and imagmagick - both based on libavif I believe

FWIW, I'm pretty sure imagemagick support is based on [libheif](https://github.com/strukturag/libheif)
