### ISSUE TITLE
resize images

### ISSUE THREAD

**Issue by skyfaller** [kornelski/cavif-rs#7]
I have an original JPEG, and a bunch of resized JPEGs at q75 (720px wide, 1080px wide, etc.). I would like to make these into identically sized AVIFs, but it seems to me that I won't get as good results if I turn the lower-quality JPEGs into AVIFs. I would expect the best results would come from resizing the original JPEG and converting those into AVIFs of different sizes, or converting the original to AVIF and then resizing that.

First, is resizing supported in cavif? If not, is this a desirable feature that could be added?

Second, if that is out of scope for cavif, how would you go about doing this on the command line? What tools would you use? Apologies if this is the wrong place to ask.

**Comment by kornelski** [comment]
You're right that 1:1 conversion between lossy formats isn't ideal. It wouldn't be too hard to add most basic scaling, but I'm afraid it will just lead to requests for more scaling modes, filtering modes, cropping, etc. until it becomes ImageMagick. So I suggest use ImageMagick:

```bash
convert image.jpg -resample 25% PNG:- | cavif - > image.avif
```
