### ISSUE TITLE
cavif 1.5.2 images are no longer valid according to windows

### ISSUE THREAD

**Issue by JSorngard** [kornelski/cavif-rs#73]
Hi!

I just updated to cavif 1.5.2 from 1.5.0 and found that the final images produced by cavif are no longer valid according to the windows file explorer and image viewer. It is very possible that this is a bug in windows related to #60, but I want to flag it just in case.

It looks like this in file explorer:
![cavif_update_result](https://github.com/kornelski/cavif-rs/assets/44257381/714e60b9-ebd3-432e-99e9-e8981a70c808)
The leftmost image was encoded with version 1.5.0, the middle is the original, and the rightmost image was encoded with 1.5.2.
Attempting to open it results in this screen:
![open_file](https://github.com/kornelski/cavif-rs/assets/44257381/baa8563a-61d7-41e4-b8cf-8d26865f8847)
The text translates as "The file in the picture can not be opened as the format is not supported or the file is damaged".
The image produced by the earlier version opens fine.

**Comment by kornelski** [comment]
Can you check 1.5.1 too?

**Comment by JSorngard** [comment]
With version 1.5.1 I get the same result:
![thumbnails](https://github.com/kornelski/cavif-rs/assets/44257381/05f79062-0058-434d-9405-cc057f18ea4d)
BUNNY3.avif is the result of encoding with version 1.5.1. It looks the same when opened:
![open_bunny3](https://github.com/kornelski/cavif-rs/assets/44257381/108fee5b-d52b-4179-9cb0-50c42dcd5008)

**Comment by kornelski** [comment]
So this is probably from switching to 10-bit depth. I've released 1.5.3 with `--depth=8` flag.
