### ISSUE TITLE
[Feature request]: Add webp format support for input images

### ISSUE THREAD

**Issue by suphamster** [kornelski/cavif-rs#74]
Since most of tools that supports it (imagemagick, nconvert, libvips, ffmpeg) are much slower than cavif (and avifenc).

**Comment by kornelski** [comment]
Lossy to lossy conversion is a bad idea. I didn't want to encourage that. In the conversion you will be losing more quality than you're saving in file size. 

WebP lossy only supports half-resolution color channels. This is a very old technique that AV1 has obsoleted, so I've deliberately haven't supported it in this tool.

So I suggest if you already have WebP, leave it.
