### ISSUE TITLE
cannot compile on debian 32bit

### ISSUE THREAD

**Issue by dioskey** [kornelski/cavif-rs#75]
Hi,
I'm trying to compile it on a debian 11 32bit with no success, trying to compile on 64bit there are no problems at all.

Here is the notice that comes up trying ti compile: undefined reference to "__time64" (and __gmtime64).

I need to use it on an old webserver to add avif support.

Is there a way to compile it in 32bit full static?
Thanks

**Comment by kornelski** [comment]
You can try compiling it for the MUSL target, which will be compatible with any Debian.

For libc targets Rust requires old-but-not-completely-obsolete versions of libc, which likely excludes older Debians.
