### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by fintelia** [kornelski/cavif-rs#77]
It would be helpful to have a release that includes https://github.com/kornelski/cavif-rs/commit/a0a3652ce8a36d4aee9c5da2ab35b4e97cd20fea. That's because without that change end-users must compile with [`resolver = "2"`](https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2) or else they will end up enabling the asm feature _even on non-wasm targets_.

**Comment by kornelski** [comment]
Done
