### ISSUE TITLE
Add compatible with HEIF

### ISSUE THREAD

**Issue by marcomsousa** [kornelski/cavif-rs#8]
Add compatible with HEIF decode.
HEIF is the default codec from Apple products, let's allow this big number of imagens to be migrated to AVIF.

You can use libheif-rs or libheif-sys

**Comment by kornelski** [comment]
Apple uses HEIC, which is H.265 video frame in a HEIF container. It's not enough to support only HEIF. It's necessary to support H.265-in-HEIF.

Unfortunately, H.265 is a commercial, patented format. Patents are wide-reaching, and make all uses of H.265, even free and open-source implementations by other people, illegal without a patent license. That free-software-killing toxicity of patents is *the* reason why AVIF exists in the first place.

I'm not going to take the risk of supporting H.265/HEIC in any of my software, before patents expire around 2033.
