### ISSUE TITLE
Detected as Malware

### ISSUE THREAD

**Issue by akavkl** [kornelski/cavif-rs#80]
Probably a false positive, but just wanna let the author know.

**Comment by kornelski** [comment]
Where, by whom?

Which version? What OS?

Did you get it from the releases page?

**Comment by akavkl** [comment]
v1.5.5 Windows from releases, flagged by Avira, caught by file scan, and blocked even after whitelisting for suspicious process.

**Comment by kornelski** [comment]
1.5.5 is okay according to Avira:

https://www.virustotal.com/gui/file/727e96a52a5f129f6878a8e56acfd5455db0fd655738ad8eeb0bd92220f66067/detection
