### ISSUE TITLE
Recent patch upgrade seems to require more recent rustc version (1.79)

### ISSUE THREAD

**Issue by antimora** [kornelski/cavif-rs#82]
Just recently we ([Burn project](https://github.com/tracel-ai/burn)) noticed that ravif requires rust 1.79 after a patch release. 

```
error: package `ravif v0.11.8` cannot be built because it requires rustc 1.79 or newer, while the currently active rustc version is 1.76.0
Either upgrade to rustc 1.79 or newer, or use
cargo update ravif@0.11.8 --precise ver
where `ver` is the latest version of `ravif` supporting rustc 1.76.0
[
```

**Comment by kornelski** [comment]
Yes, that's because `bitstream-io`, a dependency of `rav1e`, started using a feature only in Rust 1.79.

Such is life in the Rust ecosystem, where only the latest stable is supported. Support for 1.79 is going to end in 8 days, when 1.80 comes out.

**Comment by syl20bnr** [comment]
I don't understand, is that not possible to lock on finer grained version ?
If I am not mistaken the issue comes from `rav1e` where the pinned version is too loose right ?

https://github.com/xiph/rav1e/blob/master/Cargo.toml

**Comment by kornelski** [comment]
Pinning of versions is very disruptive, because it makes the project automatically incompatible with users of the newer version.

You can use `cargo update --precise $ver -p $crate` to downgrade crates in your `Cargo.lock`, but I can't do that for you without causing problems for others.

**Comment by syl20bnr** [comment]
Indeed there is no right way to fix this for all users. Thank you for the quick feedback!
